---
applications:
  - animedb
  - guillotina.contrib.catalog.pg
  - guillotina.contrib.swagger
  - guillotina.contrib.dbusers
databases:
  db:
    #storage: postgresql
    storage: DUMMY_FILE
    filename: data_file.db
    #dsn: postgresql://postgres@localhost:5432/guillotina
    read_only: false
host: "*"
port: 8282
root_user:
  password: root
auth_extractors:
  - guillotina.auth.extractors.BearerAuthPolicy
  - guillotina.auth.extractors.BasicAuthPolicy
  - guillotina.auth.extractors.WSTokenAuthPolicy
auth_token_validators:
  - guillotina.auth.validators.SaltedHashPasswordValidator
  - guillotina.auth.validators.JWTValidator
cors:
  allow_origin:
    - http://localhost:8080
    - "chrome-extension://*"
  allow_methods:
    - GET
    - POST
    - DELETE
    - HEAD
    - PATCH
    - PUT
    - OPTIONS
  allow_headers:
    - "*"
  expose_headers:
    - "*"
  allow_credentials: true
  max_age: 3660
jwt:
  secret: foobar
  algorithm: HS256
jsapps:
  +admin: guillotina:static/executioner

logging: 
  version: 1
  formatters:
    default:
      format: "%(asctime)s %(levelname)-8s %(name)-15s %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers: 
    default:
      class: logging.StreamHandler
      level: DEBUG
  loggers: 
    guillotina: 
      level: DEBUG
      handlers:
        - default 
      propagate: 1      